### ISSUE TITLE
Module type edge-case with nested `package.json`

### ISSUE THREAD

**Issue by privatenumber** [wooorm/npm-esm-vs-cjs#2]
I also implemented module type detection on https://pkg-size.dev and just wanted to let you know that I discovered that some packages have nested `package.json` to influence the type of `.js` files in the directory.

For example:
https://unpkg.com/browse/react-pdf@7.3.3/dist/cjs/package.json

**Comment by wooorm** [comment]
Heya, thanks for letting me know! 👋

I was about to add another note to the readme.
But this example is a) not popular enough to be included here, b) should be detected as dual, as it has both `import` and `require` entries in its export map!

There probably are a couple cases that get detected wrong. Let me know if you find more!
