### ISSUE TITLE
Run script on schedule using GitHub Actions 

### ISSUE THREAD

**Issue by wojtekmaj** [wooorm/npm-esm-vs-cjs#3]

**Comment by wooorm** [comment]
Hey!
I dunno, what will that really improve? Why do you want that?

npm-high-impact is where the complexity is.
If that is updated, then this can be updated.
But that takes longer to run than actions allows.

**Comment by wojtekmaj** [comment]
I was thinking, perhaps the repository could update itself, monthly, without your intervention at all :D

**Comment by wooorm** [comment]
I don’t think running this more frequently adds much. It wouldn’t take into account which packages are popular at that date, making it harder to compare, as the data is not entirely the same as the existing data / quarterly data.
Also folks don’t switch from cjs <> esm <> dual that often?

**Comment by wooorm** [comment]
Closing for now, not convinced yet that it’s an improvement!
